In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [15]:
# Load the dataset and select specific columns
df = pd.read_csv('train.csv')[['Age', 'Pclass','SibSp', 'Parch', 'Survived']]

In [16]:
df.head(5)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [17]:
# this will drop all the rows with missing values in the dataset

df.dropna(inplace=True)

In [18]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [19]:
# Split the dataset into features (X) and target variable (y)
#: (before the comma): Tells Pandas to select every single row in the dataset.
# 0:4 (after the comma): Tells Pandas to select columns starting at index 0 up to, but not including, index 4.The Result:
#  It grabs columns 0, 1, 2, and 3 across all rows and stores them in a new DataFrame called X.


X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [20]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

0.6933333333333332

### Appling Feature Construction

In [21]:
X['Family_Size'] = X['SibSp'] + X['Parch']

In [22]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size
0  22.0       3      1      0            1
1  38.0       1      1      0            1
2  26.0       3      0      0            0
3  35.0       1      1      0            1
4  35.0       3      0      0            0

In [ ]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [ ]:
myfunc(4)

In [ ]:
X['Family_type'] = X['Family_size'].apply(myfunc)
X.head()

In [ ]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)
X.head()

In [ ]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

### Feature Splitting

In [ ]:
df = pd.read_csv('train.csv')
df.head()

In [ ]:
df['Name']

In [ ]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [ ]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [ ]:
df[['Title','Name']]

In [ ]:
(df.groupby('Title').mean()['Survived']).sort_values(ascending=False)

In [ ]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [ ]:
df['Is_Married']