In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load the dataset and select specific columns
df = pd.read_csv('train.csv')[['Age', 'Pclass','SibSp', 'Parch', 'Survived']]

In [7]:
df.head(5)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [ ]:
# this will drop all the rows with missing values in the dataset

df.dropna(inplace=True)

In [9]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [ ]:
# Split the dataset into features (X) and target variable (y)
#: (before the comma): Tells Pandas to select every single row in the dataset.
# 0:4 (after the comma): Tells Pandas to select columns starting at index 0 up to, but not including, index 4.The Result:
#  It grabs columns 0, 1, 2, and 3 across all rows and stores them in a new DataFrame called X.


X = df.iloc[:,0:4]
y = df.iloc[:,-1]